### ISSUE TITLE
prepare build.gradle.kts for maven-central deploy

### ISSUE THREAD

**Issue by dominikmaeckel** [tudo-aqua/bgw-core#59]
https://github.com/tudo-aqua/z3-turnkey/blob/master/build.gradle.kts

**Comment by tillschallau** [comment]
@snaujokat Are we using `io.github.tudo-aqua` or `tools.aqua` as our groupId? In sonatype we own both, if I see that correctly.

`tools.aqua` might be better, as it is also the namespace used in the project.

**Comment by tillschallau** [comment]
A common and acceptable practice for name is to assemble it from the coordinates using Maven properties:


<name>${project.groupId}:${project.artifactId}</name>

We should discuss if we use the existing naming convention or the ones described in https://central.sonatype.org/publish/requirements/.

**Comment by snaujokat** [comment]
> @snaujokat Are we using `io.github.tudo-aqua` or `tools.aqua` as our groupId? In sonatype we own both, if I see that correctly.
> 
> `tools.aqua` might be better, as it is also the namespace used in the project.

Yes, we already use `tools.aqua` as groupId

**Comment by snaujokat** [comment]
I don't understand the question.

> A common and acceptable practice for name is to assemble it from the coordinates using Maven properties:

which name?
 
> ${project.groupId}:${project.artifactId}

this looks like the usual practice, yes.

> We should discuss if we use the existing naming convention or the ones described in https://central.sonatype.org/publish/requirements/.

but I don't see the contradiction here?!

**Comment by tillschallau** [comment]
> > @snaujokat Are we using `io.github.tudo-aqua` or `tools.aqua` as our groupId? In sonatype we own both, if I see that correctly.
> > `tools.aqua` might be better, as it is also the namespace used in the project.
> 
> Yes, we already use `tools.aqua` as groupId

If was replying to the branch "https://github.com/tudo-aqua/bgw-core/blob/MavenPublishGradleConfig/build.gradle.kts". There the groupdId is still set to 'io.github.tudo-aqua'. There is currently a significant difference between the main branch and the 'MavenPublishGradleConfig' branch.

**Comment by tillschallau** [comment]
> I don't understand the question.
> 
> > A common and acceptable practice for name is to assemble it from the coordinates using Maven properties:
> 
> which name?
> 
> > ${project.groupId}:${project.artifactId}
> 
> this looks like the usual practice, yes.
> 
> > We should discuss if we use the existing naming convention or the ones described in https://central.sonatype.org/publish/requirements/.
> 
> but I don't see the contradiction here?!

The suggestion at sonatype is that the name might be: "${project.groupId}:${project.artifactId}", where we currently only use "${project.artifactId}" as the 'name' attribute in our generated POM file.

**Comment by snaujokat** [comment]
> > > @snaujokat Are we using `io.github.tudo-aqua` or `tools.aqua` as our groupId? In sonatype we own both, if I see that correctly.
> > > `tools.aqua` might be better, as it is also the namespace used in the project.
> > 
> > 
> > Yes, we already use `tools.aqua` as groupId
> 
> If was replying to the branch "https://github.com/tudo-aqua/bgw-core/blob/MavenPublishGradleConfig/build.gradle.kts". There the groupdId is still set to 'io.github.tudo-aqua'. There is currently a significant difference between the main branch and the 'MavenPublishGradleConfig' branch.

Thanks for pointing it out. Yes, in this case, it indeed needs to be changed.

**Comment by snaujokat** [comment]
> > I don't understand the question.
> > > A common and acceptable practice for name is to assemble it from the coordinates using Maven properties:
> > 
> > 
> > which name?
> > > ${project.groupId}:${project.artifactId}
> > 
> > 
> > this looks like the usual practice, yes.
> > > We should discuss if we use the existing naming convention or the ones described in https://central.sonatype.org/publish/requirements/.
> > 
> > 
> > but I don't see the contradiction here?!
> 
> The suggestion at sonatype is that the name might be: "${project.groupId}:${project.artifactId}", where we currently only use "${project.artifactId}" as the 'name' attribute in our generated POM file.

I think neither is really acceptable as "human-readable" name for a project. I suggest we use "BoardGameWork Core Library"

**Comment by tillschallau** [comment]
Changed groupIp and pom name in commit 604e02567eec41fd149618afc0620b216d0e2de6

**Comment by snaujokat** [comment]
Deploy to Sonatype's staging area works now and all their validations pass.

However, I think that our `-sources.jar` and `-javadoc.jar` are not correct yet. The sources jar kontains a `kotlin` folder with duplicates of all source files, and the javadoc jar has a strange structure, so that IntelliJ did not accept it as documentation from within the War game project.

**Comment by snaujokat** [comment]
Also, the generated jar still has traces of maumau (empty directories, which I don't know where they come from)

![Uploading Screenshot_2021-07-13_13-27-51.png…]()

**Comment by snaujokat** [comment]
multi-module project removed maumau, -sources.jar is fixed, -javadoc.jar now contains dokkaJavadoc instead of dokkaHtml.

Unfortunately, IntelliJ still does not recognize the -javadoc.jar, so that documentation is properly visualized in the IDE. We might have a look at it at a later point, but for now the -sources.jar works and provides Kdoc as well as "jump into source", so the effect is negligible.
