### ISSUE TITLE
Show exceptions (in a more annoying way)

### ISSUE THREAD

**Issue by snaujokat** [tudo-aqua/bgw-core#69]
Currently, the framework silently ignores all exceptions that occur somewhere in user-provided code. It just prints out the stacktrace. This can easily be missed and when run as standalone JAR from some GUI file explorer, it won't be visible at all.

I suggest we introduce a more visible (and annoying!) form of exception presentation. Maybe simply as a popup window. The application/framework should still be as resilient as it is now, but exceptions shouldn't be as easily missed.

@tudo-aqua/sopra what do you think?

**Comment by tillschallau** [comment]
If it is not too complicated to implement we could try it out and see what impact the display might have.

**Comment by dominikmaeckel** [comment]
Added Dialogs including default exception handler. In my opinion this is a good extension to the framework.
Exceptions still get printed to the console for easier code jumping.
Inspect this solution and comment or close the issue.

**Comment by snaujokat** [comment]
Good extension, I agree. It is sufficiently annoying, so that proper error handling can't be ignored anymore :)
