### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by tillschallau** [tudo-aqua/bgw-core#81]
https://github.com/tudo-aqua/bgw-core/blob/0dd6dd9c8943e992cfa65fd7aaf5204d485d6b7f/src/main/kotlin/tools/aqua/bgw/core/BoardGameApplication.kt#L47

The description, on when the background visual is shown, should be more clear.

**Comment by fabiankluempers** [comment]
Check improved doc and close the issue if its sufficient now.
