### ISSUE TITLE
Add overwritten documentation annotation

### ISSUE THREAD

**Issue by tillschallau** [tudo-aqua/bgw-core#87]
https://github.com/tudo-aqua/bgw-core/blob/061b3e5cca22ad62c61d404c89055e4b2b3052bf/src/main/kotlin/tools/aqua/bgw/elements/gameelements/GameElementView.kt#L35

Overwriting a documentation annotation removes the inherited documentation. Therefore, add the overwritten documentation here manually.

**Comment by dominikmaeckel** [comment]
Overriding the documentation is intended as GameElementView always throws an Exception when calling removeChild(). The error was the "if".
