### ISSUE TITLE
Reference "Alignment" in Documentation when changing "CenterModes"

### ISSUE THREAD

**Issue by tillschallau** [tudo-aqua/bgw-core#88]
https://github.com/tudo-aqua/bgw-core/blob/061b3e5cca22ad62c61d404c89055e4b2b3052bf/src/main/kotlin/tools/aqua/bgw/elements/layoutviews/GridLayoutView.kt#L121

You should add a reference to "Alignment" in the whole class for the methods where you set the "CenterModes".

Additionally, check an unified spelling of "CenterMode". Sometimes its uppercase, sometimes not.

**Comment by dominikmaeckel** [comment]
Added reference to "Alignment", but I did not find any upper case "CenterMode" - maybe it has already been fixed?

**Comment by tillschallau** [comment]
"Centering Mode" is mostly lowercase (lines 105, 114, 127,...) and sometimes uppercase (lines 119, 143, 154)

**Comment by dominikmaeckel** [comment]
> 
> 
> "Centering Mode" is mostly lowercase (lines 105, 114, 127,...) and sometimes uppercase (lines 119, 143, 154)

I searched for CenterMode without the space so I did not find this. Fixed now.
